[ch33107] rebuild magento docker container: * combine run commands into a single item * make xdebug an optional component at build param based off of the build arg BUILD_ENABLE_XDEBUG=[true/false] * remove the supervisor dependency and the associated user account issues * set a www-data group sticky bit on /var/www/html * consolidate docker-compose.yaml into a single file for more idiomatic operation * expose extra envs in docker-compose.yaml update .env.defaults / .env.schema * remove php dependencies from init scripts * utilize runuser to ensure setup scripts are run as www-data * start cron service on container start * added docker-compose.override.yaml to .gitignore to allow for special docker configs

diff --git a/magento/Dockerfile b/magento/Dockerfile
--- a/magento/Dockerfile
+++ b/magento/Dockerfile
@@ -9,76 +9,79 @@ ENV MAGEPASS=2f7e27231024a6cbc3e075f5a74b8264e6badb56
 ENV MAGENTO_INSTALLER_DIR=/tmp
 
 RUN cd "${MAGENTO_INSTALLER_DIR}" && \
-  curl -O "https://${MAGEUSER}:${MAGEPASS}@www.magentocommerce.com/products/downloads/file/Magento-CE-${MAGENTO_VERSION}_sample_data.zip"
+  curl -O "https://${MAGEUSER}:${MAGEPASS}@www.magentocommerce.com/products/downloads/file/Magento-CE-${MAGENTO_VERSION}.zip"
+
+ARG BUILD_ENABLE_XDEBUG=false
 
 # Install generally useful utilities
-RUN apt update -y && \
-  apt install -y jq unzip
-
+RUN apt update -y \
+  && apt install -y \
+    jq unzip \
+    default-mysql-client \
 # Install native libraries for magento required php extensions
-RUN apt install -y libicu-dev \
-    zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev \
+    libicu-dev \
+    zlib1g-dev \
+    libpng-dev \
+    libjpeg-dev \
+    libfreetype6-dev \
     libxslt1-dev \
-    libzip-dev
-
+    libzip-dev \
 # Install cron to support Magento's cron jobs
-RUN apt install -y cron supervisor
-
+    cron \
+#cleanup apt packages
+  && rm -rf /var/lib/apt/lists/* \
 # Set the php.ini file for development
-RUN mv "${PHP_INI_DIR}/php.ini-development" "${PHP_INI_DIR}/php.ini"
-
+  && mv "${PHP_INI_DIR}/php.ini-development" "${PHP_INI_DIR}/php.ini" \
 # Change php memory limit to '-1' // Magento wants > 2GB
-RUN sed -i 's/^\(memory_limit =\).*$/\1 -1/' "${PHP_INI_DIR}/php.ini"
-
+  && sed -i 's/^\(memory_limit =\).*$/\1 -1/' "${PHP_INI_DIR}/php.ini" \
 # Install mysql extensions
-RUN docker-php-ext-install mysqli pdo pdo_mysql
-
+  && docker-php-ext-install mysqli pdo pdo_mysql \
 # Install Magento required php extensions
-RUN docker-php-ext-configure gd \
-  --with-freetype-dir=/usr/include \
-  --with-jpeg-dir=/usr/include \
+  && docker-php-ext-configure gd \
+    --with-freetype-dir=/usr/include \
+    --with-jpeg-dir=/usr/include \
   && docker-php-ext-install gd \
-    intl bcmath xsl soap zip sockets
-
+    intl bcmath xsl soap zip sockets \
 # Enable required apache modules
-RUN a2enmod expires headers rewrite
-
+  && a2enmod expires headers rewrite \
+  && cd "${MAGENTO_INSTALLER_DIR}" \
+  &&  unzip -qq "./Magento-CE-${MAGENTO_VERSION}.zip" -d /var/www/html \
+# `/var/www` is the home directory for user `www-data`
+  && chown -R www-data:www-data /var/www \
 # Install Xdebug
-RUN pecl install xdebug \
-  && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" \
-    > /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
+  && [ $BUILD_ENABLE_XDEBUG = "true" ] && pecl install xdebug || true \
+  && [ $BUILD_ENABLE_XDEBUG = "true" ] && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" \
+    > /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini || true \
+  && chown -R www-data:www-data /var/www/html && chmod -R g+s /var/www/html
 
 # Set the run user/group
 # .. We could do everything as `root`, but this is closer to what
 #    a non-dev instance would run as.  The container must be run
 #    with `--sysctls net.ipv4.ip_unprivileged_port_start=0` when
 #    this is set to non-root and binding to port < 1024.
-ENV APACHE_RUN_USER=www-data
-ENV APACHE_RUN_GROUP=www-data
 
-# `/var/www` is the home directory for user `www-data`
-RUN chown www-data:www-data /var/www
-USER www-data
-WORKDIR /var/www
 
-RUN cd "${MAGENTO_INSTALLER_DIR}" && \
-  unzip -qq "./Magento-CE-${MAGENTO_VERSION}_sample_data.zip" -d /var/www/html
-
-# Set `composer` path
-ENV COMPOSER_HOME=/var/www/html/var/composer_home
-
-ENV MAGE_COMPOSER_REPO_PUBKEY=1b8325eb6d792fe22c0fb83f65150281
-ENV MAGE_COMPOSER_REPO_PRIVKEY=d68ff7618b2f3118a0342d7f914848c8
+WORKDIR /var/www/html
 
 COPY --chown=www-data:www-data \
-  create-magento-db.php \
+  check-db-status.sh \
   setup-and-run.sh \
   setup-magento.sh \
   setup-protect.sh \
   setup-update-config.sh \
-  try-connect-magento-db.php \
-  wait-for-protect.sh ./
+  wait-for-protect.sh /tmp/
 
-USER root
-COPY ./supervisord.conf .
-CMD ["/usr/bin/supervisord", "-c", "./supervisord.conf"]
+# Set `composer` path
+ENV COMPOSER_HOME=/var/www/html/var/composer_home
+ENV APACHE_RUN_USER=www-data
+ENV APACHE_RUN_GROUP=www-data
+ENV MAGE_COMPOSER_REPO_PUBKEY=1b8325eb6d792fe22c0fb83f65150281
+ENV MAGE_COMPOSER_REPO_PRIVKEY=d68ff7618b2f3118a0342d7f914848c8
+ENV MAGENTO_INSTALL_DIR=/var/www/html
+ENV BIN_MAGENTO="${MAGENTO_INSTALL_DIR}/bin/magento"
+ENV BIN_COMPOSER="${MAGENTO_INSTALL_DIR}/vendor/composer/composer/bin/composer"
+
+# Run
+# USER www-data
+# CMD ["/usr/bin/supervisord", "-c", "/tmp/supervisord.conf"]
+CMD ["/bin/bash", "/tmp/setup-and-run.sh"]
